version: '3.8'

services:
  db:
    container_name: sustainability_project_db
    image: postgres
    restart: always
    ports:
      - 1004:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
  pgadmin:
    container_name: sustainability_project_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - '1104:80'
    depends_on:
      - db

volumes:
  db_data:
